use tienda_informatica_final;
-- MySQL Script generated by MySQL Workbench
-- Sat Nov 15 19:29:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tienda_informatica_final
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS `tienda_informatica_final` ;

-- -----------------------------------------------------
-- Schema tienda_informatica_final
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda_informatica_final` DEFAULT CHARACTER SET utf8 ;
USE `tienda_informatica_final` ;

-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`Alquiler`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`Alquiler` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`Alquiler` (
  `idAlquiler` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idAlquiler`),
  CONSTRAINT `fk_Alquiler_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `tienda_informatica_final`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alquiler_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `tienda_informatica_final`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`Categoria_alta_tecnologia`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`Categoria_alta_tecnologia` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`Categoria_alta_tecnologia` (
  `categoria_producto_idcategoria` INT NOT NULL,
  PRIMARY KEY (`categoria_producto_idcategoria`),
  CONSTRAINT `fk_Categoria_alta_tecnologia_categoria_producto`
    FOREIGN KEY (`categoria_producto_idcategoria`)
    REFERENCES `tienda_informatica_final`.`categoria_producto` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`Cliente`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `primer_nombre` VARCHAR(20) NOT NULL,
  `primer_apellido` VARCHAR(20) NOT NULL,
  `segundo_apellido` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `Telefono_idTelefono` INT NOT NULL,
  `Direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC),
  CONSTRAINT `fk_Cliente_Telefono1`
    FOREIGN KEY (`Telefono_idTelefono`)
    REFERENCES `tienda_informatica_final`.`Telefono` (`idTelefono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Direccion1`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `tienda_informatica_final`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`Detalle_alta_tecnologia`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`Detalle_alta_tecnologia` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`Detalle_alta_tecnologia` (
  `idDetalle_alta_tecnologia` INT NOT NULL AUTO_INCREMENT,
  `pais_origen` VARCHAR(30) NOT NULL,
  `fecha_fabricacion` DATE NOT NULL,
  `Empresa_fabricante_idEmpresa_fabricante` INT NOT NULL,
  PRIMARY KEY (`idDetalle_alta_tecnologia`),
  CONSTRAINT `fk_Detalle_alta_tecnologia_Empresa_fabricante1`
    FOREIGN KEY (`Empresa_fabricante_idEmpresa_fabricante`)
    REFERENCES `tienda_informatica_final`.`Empresa_fabricante` (`idEmpresa_fabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`Direccion`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`Direccion` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`Direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(30) NOT NULL,
  `ciudad` VARCHAR(30) NOT NULL,
  `calle` VARCHAR(40) NOT NULL,
  `barrio` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idDireccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`Empresa_fabricante`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`Empresa_fabricante` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`Empresa_fabricante` (
  `idEmpresa_fabricante` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `numreo_empleados` INT NOT NULL,
  PRIMARY KEY (`idEmpresa_fabricante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`Empresa_fabricante`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`Empresa_fabricante` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`Empresa_fabricante` (
  `idEmpresa_fabricante` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `numreo_empleados` INT NOT NULL,
  PRIMARY KEY (`idEmpresa_fabricante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`Producto_proveedor`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`Producto_proveedor` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`Producto_proveedor` (
  `idProducto_proveedor` INT NOT NULL AUTO_INCREMENT,
  `fecha_adquisicion` DATE NOT NULL,
  `producto_idproducto` INT NOT NULL,
  `proveedor_idproveedor` INT NOT NULL,
  PRIMARY KEY (`idProducto_proveedor`),
  CONSTRAINT `fk_Producto_proveedor_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `tienda_informatica_final`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_proveedor_proveedor1`
    FOREIGN KEY (`proveedor_idproveedor`)
    REFERENCES `tienda_informatica_final`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`Telefono`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`Telefono` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`Telefono` (
  `idTelefono` INT NOT NULL AUTO_INCREMENT,
  `numero_principal` VARCHAR(20) NOT NULL,
  `numero_secundario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idTelefono`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`Transaccion`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`Transaccion` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`Transaccion` (
  `idTransaccion` INT NOT NULL AUTO_INCREMENT,
  `precio` DECIMAL(10,2) NOT NULL,
  `tipo_pago` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`idTransaccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`Venta`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`Venta` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`Venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `Transaccion_idTransaccion` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idVenta`),
  CONSTRAINT `fk_Venta_Transaccion1`
    FOREIGN KEY (`Transaccion_idTransaccion`)
    REFERENCES `tienda_informatica_final`.`Transaccion` (`idTransaccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `tienda_informatica_final`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `tienda_informatica_final`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`categoria_alquilables`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`categoria_alquilables` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`categoria_alquilables` (
  `categoria_producto_idcategoria` INT NOT NULL,
  PRIMARY KEY (`categoria_producto_idcategoria`),
  CONSTRAINT `fk_categoria_alquilables_categoria_producto1`
    FOREIGN KEY (`categoria_producto_idcategoria`)
    REFERENCES `tienda_informatica_final`.`categoria_producto` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`categoria_producto`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`categoria_producto` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`categoria_producto` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`categoria_servicios_tecnicos`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`categoria_servicios_tecnicos` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`categoria_servicios_tecnicos` (
  `categoria_producto_idcategoria` INT NOT NULL,
  PRIMARY KEY (`categoria_producto_idcategoria`),
  CONSTRAINT `fk_categoria_servicios_tecnicos_categoria_producto1`
    FOREIGN KEY (`categoria_producto_idcategoria`)
    REFERENCES `tienda_informatica_final`.`categoria_producto` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`producto`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`producto` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `Detalle_alta_tecnologia_idDetalle_alta_tecnologia` INT NULL,
  `categoria_producto_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idproducto`),
  CONSTRAINT `fk_producto_Detalle_alta_tecnologia1`
    FOREIGN KEY (`Detalle_alta_tecnologia_idDetalle_alta_tecnologia`)
    REFERENCES `tienda_informatica_final`.`Detalle_alta_tecnologia` (`idDetalle_alta_tecnologia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_categoria_producto1`
    FOREIGN KEY (`categoria_producto_idcategoria`)
    REFERENCES `tienda_informatica_final`.`categoria_producto` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`proveedor`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`proveedor` (
  `idproveedor` INT NOT NULL AUTO_INCREMENT,
  `NIF` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`idproveedor`),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`servicio_tecnico`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`servicio_tecnico` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`servicio_tecnico` (
  `idservicio_tecnico` INT NOT NULL AUTO_INCREMENT,
  `detalles_servicio` VARCHAR(200) NOT NULL,
  `fecha_servicio_tecnico` DATE NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`idservicio_tecnico`),
  CONSTRAINT `fk_servicio_tecnico_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `tienda_informatica_final`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicio_tecnico_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `tienda_informatica_final`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tienda_informatica_final`.`usuario_sistema`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `tienda_informatica_final`.`usuario_sistema` ;

CREATE TABLE IF NOT EXISTS `tienda_informatica_final`.`usuario_sistema` (
  `idusuario_sistema` INT NOT NULL AUTO_INCREMENT,
  `primer_nombre` VARCHAR(20) NOT NULL,
  `primer_apellido` VARCHAR(20) NULL,
  `DNI` VARCHAR(20) NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  `contraseña` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idusuario_sistema`),
  UNIQUE INDEX `dni_UNIQUE` (`DNI` ASC),
  UNIQUE INDEX `contraseña_UNIQUE` (`contraseña` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
